### PR TITLE
Move error codes to docs, delete other ors/docs

### LINKED ISSUE #1069: Integrate openrouteservice/docs into docs
#### Here's what I did
Search for error codes

---
#### Here's what I got
https://github.com/GIScience/openrouteservice/blob/master/openrouteservice/docs/services/error_codes.md

---
#### Here's what I was expecting
Not more than one source for documentation apart from docs.

---
#### Here's what I think could be improved
They could be merged

### PR DESCRIPTION
**Pull request by koebi**
### Pull Request Checklist

- [x] 1. I have [**rebased**][rebase] the latest version of the master branch into my feature branch and all conflicts
         have been resolved.
- [x] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the
         [Unreleased] heading.
- [ ] ~3. I have documented my code using JDocs tags.~
- [ ] ~4. I have removed unnecessary commented out code, imports and System.out.println statements.~
- [ ] ~5. I have written JUnit tests for any new methods/classes and ensured that they pass.~
- [ ] ~6. I have created API tests for any new functionality exposed to the API.~
- [ ] ~7. If changes/additions are made to the ors-config.json file, I have added these to the [ors config documentation][config]
         along with a short description of what it is for, and documented this in the Pull Request (below).~
- [ ] ~8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing~
- [x] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [ ] ~10. For new features or changes involving building of graphs, I have tested on a larger dataset
          (at least Germany), and the graphs build without problems (i.e. no out-of-memory errors).~
- [ ] ~11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the
          importer etc.), I have generated longer distance routes for the affected profiles with different options
          (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end
          points generated from the current live ORS.
          If there are differences then the reasoning for these **MUST** be documented in the pull request.~
- [x] 12. I have written in the Pull Request information about the changes made including their intended usage
          and why the change was needed.
- [ ] ~13. For changes touching the API documentation, I have tested that the API playground [renders correctly][api].~

Fixes #1069.

### Information about the changes
All backend documentation has been moved to the docs-folder.
These have been overlooked in the original PR.
All other files are not needed anymore:

The `*_request.json`-files seem to be exemplary requests superseded by
the playground.  BikeSpeedCalculations are easily derived again from an
online bike speed calculator.  Everything in `eurostat` has probably
been added for testing reasons and is no longer needed.

[config]: https://GIScience.github.io/openrouteservice/installation/Configuration.html
[api]: https://gitlab.gistools.geog.uni-heidelberg.de/giscience/openrouteservice-infrastructure/ors-docs-api#test-new-ors-documentation
[rebase]: https://github.com/GIScience/openrouteservice/blob/master/CONTRIBUTE.md#pull-request-guidelines

### CODE REVIEW

**Review by takb — APPROVED** [review]
ok

**Comment by koebi** [comment]
As discussed, I have archived both files from the `eurostat`-folder.
From my site, this can be merged.

**Comment by takb** [comment]
automated testing seems to have some problem, I'll have to figure out how to restart it somehow... tomorrow.

**Comment by koebi** [comment]
After talking with @MichaelsJP it seems like the `eurostat`-directory is still somewhat needed.
I'll move it to `src/resources/resources/services/isochrones/eurostat`, since I feel it belongs there more than in a separate `docs`-folder - it isn't documenting anything, tbh^^

**Comment by takb** [comment]
Cool @koebi, maybe another commit will restart the tests since I could not find a way to do anything about the stuck test run displayed below...

**Pull request merged**
