### PR TITLE
742 fix docker

### LINKED ISSUE #742: New docker containers always use the default app.config
It's very annoying: whenever a new container is created (e.g. when just changing some env var in `docker-compose.yml`) the new container reads the default `app.config` provided by the image. Regardless if the user actually has a valid config in `./ors-conf`. 

Not hard to remedy:

The problem is that `mvn package` is run in the image itself, which packages the default `app.config` into the WAR file. So currently there's no way to access the `app.config` Tomcat will use since it's inside the WAR.

The lines 
```
    mvn -q -f /ors-core/openrouteservice/pom.xml package -DskipTests && \
    cp -f /ors-core/openrouteservice/target/*.war /usr/local/tomcat/webapps/ors.war && \ 
```
need to be in `docker-entrypoint.sh`, not in the `Dockerfile`, with some logic so we don't package needlessly if nothing changed.

### PR DESCRIPTION
**Pull request by nilsnolde**
### Pull Request Checklist

- [x] 1. I have [**rebased**](https://github.com/GIScience/openrouteservice/blob/master/CONTRIBUTE.md#pull-request-guidelines) the latest version of the master branch into my feature branch and all conflicts have been resolved.
- [x] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the [Unreleased] heading.
- [ ] 3. I have documented my code using JDocs tags.
- [ ] 4. I have removed unnecessary commented out code, imports and System.out.println statements.
- [ ] 5. I have written JUnit tests for any new methods/classes and ensured that they pass.
- [ ] 6. I have created API tests for any new functionality exposed to the API.
- [ ] 7. If changes/additions are made to the app.config file, I have added these to the app.config wiki page on github along with a short description of what it is for, and documented this in the Pull Request (below).
- [ ] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [x] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [ ] 10. For new features or changes involving building of graphs, I have tested on a larger dataset (at least Germany) and the graphs build without problems (i.e. no out-of-memory errors).
- [ ] 11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the importer etc.), I have generated longer distance routes for the affected profiles with different options (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end points generated from the current live ORS. If there are differences then the reasoning for these **MUST** be documented in the pull request.
- [x] 12. I have written in the Pull Request information about the changes made including their intended usage and why the change was needed.

Fixes #742 .

### Information about the changes
- Key functionality added: 
  - default `app.config.sample` from `./openrouteservice/src/main/resources/app.config.sample` is used to build the image
  - be aware the image changes the `app.config` to 
    - only build `car` instead of all profiles
    - `init_threads: 1` since > 1 can cause issues
    - changes all paths to docker image paths
  - uses the default `heidelberg.osm.gz`
- Reason for change: Before we had two `app.config`, one for the native Java app, one for docker. This PR removes that maintenance burden.

### CODE REVIEW

**Comment by nilsnolde** [comment]
some git shit happened. note to self: def squash merge!

**Comment by LittleBoxOfChicken** [comment]
Coming from [the ask.openrouteservice.org thread](https://ask.openrouteservice.org/t/own-hosted-openrouteservice-instance-not-working/1800/9?u=littleboxofchicken).

This does indeed fix the issue for me. 😃
Thanks a bunch, Nils.

**Comment by nilsnolde** [comment]
Great, thanks for the quick feedback, Jari!

**Review by MichaelsJP — APPROVED** [review]

**Comment by MichaelsJP** [comment]
Looking good. Thanks @nilsnolde

**Pull request merged**
