### PR TITLE
Fix open spaces graph builder

### LINKED ISSUE #1186: Graph builder for open spaces fails to add new edges
Apparently the functionality of in-field routing once implemented in ORS and described in a [blogpost](http://k1z.blog.uni-heidelberg.de/2017/11/27/routing-through-open-spaces-%e2%80%93-a-performance-comparison-of-algorithms/) doesn't work at the moment, as noted by @Robot8A [in the forum](https://ask.openrouteservice.org/t/labs-openrouteservice-open-areas/3946).

 The main problem seems to lie in the following placeholder method which prevents any new edges generated by `InFieldGraphBuilder` to be added to the graph.

https://github.com/GIScience/openrouteservice/blob/7cba0a4d0c6a2ad259d4006b23f84bb7ff800848/openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/OSMDataReaderContext.java#L49-L51

### PR DESCRIPTION
**Pull request by aoles**
### Pull Request Checklist

- [x] 1. I have [**rebased**][rebase] the latest version of the master branch into my feature branch and all conflicts
         have been resolved.
- [x] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the
         [Unreleased] heading.
- [ ] 3. I have documented my code using JDocs tags.
- [x] 4. I have removed unnecessary commented out code, imports and System.out.println statements.
- [ ] 5. I have written JUnit tests for any new methods/classes and ensured that they pass.
- [ ] 6. I have created API tests for any new functionality exposed to the API.
- [ ] 7. If changes/additions are made to the ors-config.json file, I have added these to the [ors config documentation][config]
         along with a short description of what it is for, and documented this in the Pull Request (below).
- [x] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [x] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [ ] 10. For new features or changes involving building of graphs, I have tested on a larger dataset
          (at least Germany), and the graphs build without problems (i.e. no out-of-memory errors).
- [ ] 11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the
          importer etc.), I have generated longer distance routes for the affected profiles with different options
          (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end
          points generated from the current live ORS.
          If there are differences then the reasoning for these **MUST** be documented in the pull request.
- [x] 12. I have written in the Pull Request information about the changes made including their intended usage
          and why the change was needed.
- [ ] 13. For changes touching the API documentation, I have tested that the API playground [renders correctly][api].

Fixes #1186.

**IMPORTANT**: This PR is set-up to run against GH v0.13.22 which is expected to include https://github.com/GIScience/graphhopper/pull/50.

### Information about the changes
- Allows enabling of a specialized graph builder which generates additional edges in open spaces.

### Examples and reasons for differences between live ORS routes, and those generated from this pull request
- See examples in the [blogpost](http://k1z.blog.uni-heidelberg.de/2017/11/27/routing-through-open-spaces-%e2%80%93-a-performance-comparison-of-algorithms/).

### Required changes to ors config (if applicable)

In order to enable the additional graph processor add the following to a given profile definition.

```
"graph_processors": {
    "InField": {}
}
```

[config]: https://GIScience.github.io/openrouteservice/installation/Configuration.html
[api]: https://gitlab.gistools.geog.uni-heidelberg.de/giscience/openrouteservice-infrastructure/ors-docs-api#test-new-ors-documentation
[rebase]: https://github.com/GIScience/openrouteservice/blob/master/CONTRIBUTE.md#pull-request-guidelines

### CODE REVIEW

**Comment by koebi** [comment]
Hey,

as discussed, the needed additional graph processor configuration in the `ors-config.json` should be documented.
I think the best place for this is [this file](https://github.com/GIScience/openrouteservice/blob/master/docs/installation/Configuration.md), rendered [here](https://giscience.github.io/openrouteservice/installation/Configuration.html).

**Review by takb — APPROVED** [review]
lgtm

**Comment by aoles** [comment]
Thanks @takb ! Actually, I was not quite done with this PR yet. As pointed out by @koebi , the documentation of graph processor is missing and still needs to be added.

**Comment by takb** [comment]
sorry, I've restored the branch, just open a new PR for the docs

**Comment by aoles** [comment]
No worries, thanks @takb!

**Pull request merged**
