### PR TITLE
[Snyk] Upgrade org.ow2.asm:asm from 9.0 to 9.4

### PR DESCRIPTION
**Pull request by tyrasd**
<p>This PR was automatically created by Snyk using the credentials of a real user.</p><br /><h3>Snyk has created this PR to upgrade org.ow2.asm:asm from 9.0 to 9.4.</h3>

:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.
<hr/>

- The recommended version is **4 versions** ahead of your current version.
- The recommended version was released **4 months ago**, on 2022-10-02.

<hr/>

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs.*

For more information:  

🧐 [View latest project report](https://app.snyk.io/org/thegreatrefrigerator/project/4fd92117-2780-4579-9503-a800beb4da3b?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/thegreatrefrigerator/project/4fd92117-2780-4579-9503-a800beb4da3b/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/thegreatrefrigerator/project/4fd92117-2780-4579-9503-a800beb4da3b/settings/integration?pkg&#x3D;org.ow2.asm:asm&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr#auto-dep-upgrades)

### CODE REVIEW

**Comment by koebi** [comment]
…I'm wondering whether we need this at all. Currently, all API tests run with this dependency commented out (or at least I think so) and I can't find any usage of asm anywhere… 

The maven:surefire plugin apparently [depends on asm](https://maven.apache.org/surefire/maven-surefire-plugin/dependencies.html), and we might consider upgrading the plugin to 3.0 or higher, but there's no need to have the asm dependency directly in the API test.

**Comment by MichaelsJP** [comment]
I'd say let's kick the dependency out, if not needed. Fewer dependencies to care about.

**Comment by koebi** [comment]
I removed the dependency, let's see whether automated testing is successful…

**Review by koebi — APPROVED** [review]
LGTM :)

**Pull request merged**
