### PR TITLE
Time dependent pedestrian routing

### PR DESCRIPTION
**Pull request by Robot8A**
### Pull Request Checklist

- [x] 1. I have [**rebased**][rebase] the latest version of the master branch into my feature branch and all conflicts
         have been resolved.
- [x] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the
         [Unreleased] heading.
- [X] 3. I have documented my code using JDocs tags.
- [X] 4. I have removed unnecessary commented out code, imports and System.out.println statements.
- [X] 5. I have written JUnit tests for any new methods/classes and ensured that they pass.
- [ ] 6. I have created API tests for any new functionality exposed to the API.
- [ ] 7. If changes/additions are made to the ors-config.json file, I have added these to the [ors config documentation][config]
         along with a short description of what it is for, and documented this in the Pull Request (below).
- [x] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [ ] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [ ] 10. For new features or changes involving building of graphs, I have tested on a larger dataset
          (at least Germany), and the graphs build without problems (i.e. no out-of-memory errors).
- [X] 11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the
          importer etc.), I have generated longer distance routes for the affected profiles with different options
          (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end
          points generated from the current live ORS.
          If there are differences then the reasoning for these **MUST** be documented in the pull request.
- [X] 12. I have written in the Pull Request information about the changes made including their intended usage
          and why the change was needed.
- [ ] 13. For changes touching the API documentation, I have tested that the API playground [renders correctly][api].

Fixes # .

### Information about the changes
- Key functionality added: Extend time dependent routing to pedestrians. Changed FootFlagEncoder.java inspired by the changes done to CommonBikeFlagEncoder.java. Created testTimeDependent() in PedestrianFlagEncoderTest.java().
- Reason for change: Extend this feature to users that are not in vehicles, as streets may also change for them. Part of my Master's thesis work.

### Examples and reasons for differences between live ORS routes, and those generated from this pull request
- Pedestrian routing is affected, example of where such thing happens: https://www.openstreetmap.org/way/399423763

R script illustrating the new functionality:

```R
library(openrouteservice)
library(leaflet)

options(openrouteservice.url = "http://localhost:8082/ors")

coordinates = data.frame(lng = c(16.373222, 16.37348), 
                         lat = c(48.217166, 48.217874))
profile = ors_profile("walking")

ref <- ors_directions(coordinates, profile)
res <- ors_directions(coordinates, profile, departure = "2022-09-15T02:00")

leaflet() %>%
  addTiles() %>%
  fitBBox(res$bbox) %>%
  addGeoJSON(ref, fill=FALSE) %>%
  addGeoJSON(res, fill=FALSE, col="red") %>%
  addMarkers(coordinates$lng, coordinates$lat)

```
image

### Required changes to ors config (if applicable)
- Add |conditional_access=true to the necessary profiles

[config]: https://GIScience.github.io/openrouteservice/installation/Configuration.html
[api]: https://gitlab.gistools.geog.uni-heidelberg.de/giscience/openrouteservice-infrastructure/ors-docs-api#test-new-ors-documentation
[rebase]: https://github.com/GIScience/openrouteservice/blob/master/CONTRIBUTE.md#pull-request-guidelines

### CODE REVIEW

**Comment by Robot8A** [comment]
Comments about checklist:
1. I didn't manage to rebase, so I merged with the conflict errors dialog in GitHub website.
6. No new functionality in the API, just extended previous functionality to other profiles.
7. No new changes  to config file, just extended previous functionality to other profiles.
9. Changes not from issue
10. Sadly my computer is not powerful enough to test that (I only have a laptop-tablet convertible with very limited specs). Would love if any of you could test it for me.

**Comment by aoles** [comment]
Thanks a lot for your contribution @Robot8A! I will get back to you with a review soon.

**Comment by takb** [comment]
Currently the CI test can't run due to a NPE in the wheelchair profile (probably because `WheelchairFlagEncoder` extends `FootFlagEncoder`). Either @Robot8A fixes in his fork or we need to pull this in a separate branch and fix the issue there.

**Comment by Robot8A** [comment]
Fixed!

**Comment by takb** [comment]
Thanks, we'll merge as soon as @aoles had time to review!

**Review by aoles — CHANGES_REQUESTED** [review]
Nice work @Robot8, thanks again for your contribution!

While overall things look good, I believe there are still a few adaptations necessary in order to make conditional access restrictions fully functional under certain circumstances. In particular, ways blocked by default but conditionally open are currently not properly resolved as such. This is so because the lines  https://github.com/GIScience/openrouteservice/blob/e34a67758e7e31a5f2b768741d8b480c47abed3c/openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/flagencoders/FootFlagEncoder.java#L228-L229 should read 
```
if (way.hasTag(restrictions, restrictedValues))
    return isRestrictedWayConditionallyPermitted(way);
```
as only ways labelled with `Access.PERMITTED` or `Access.RESTRICTED` are recognized as having conditional access which is resolved at query time. 

Similar applies to non-highways such as railway platforms where lines
https://github.com/GIScience/openrouteservice/blob/e34a67758e7e31a5f2b768741d8b480c47abed3c/openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/flagencoders/FootFlagEncoder.java#L333-L336
need to be replaced by 
```{java}
if (way.hasTag(restrictions, restrictedValues))
                acceptPotentially = isRestrictedWayConditionallyPermitted(way, acceptPotentially);
```

Last but not least, lines https://github.com/GIScience/openrouteservice/blob/e34a67758e7e31a5f2b768741d8b480c47abed3c/openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/flagencoders/FootFlagEncoder.java#L224-L225 are now obsolete and you might want to remove them.

Sample unit test to cover the above cases are:

```
    @Test
    public void testHighwayConditionallyOpen(){
        assertTrue(encodingManager.hasConditionalAccess());

        way = generatePedestrianWay();
        way.setTag("access", "no");
        way.setTag("access:conditional", "yes @ (15:00-19:30)");

        assertTrue(flagEncoder.getAccess(way).isConditional());
    }

    @Test
    public void testNonHighwayConditionallyOpen(){
        assertTrue(encodingManager.hasConditionalAccess());

        way.setTag("railway", "platform");
        way.setTag("access", "no");
        way.setTag("access:conditional", "yes @ (5:00-23:30)");

        assertTrue(flagEncoder.getAccess(way).isConditional());
    }
```

I leave it as an exercise to you to figure out how to make the following test pass :)

```
    @Test
    public void testNonHighwayConditionallyClosed(){
        assertTrue(encodingManager.hasConditionalAccess());

        way.setTag("railway", "platform");
        way.setTag("access:conditional", "no @ (5:00-23:30)");

        assertTrue(flagEncoder.getAccess(way).isConditional());
    }
```

Cheers,
Andrzej

**Comment by Robot8A** [comment]
Thanks @aoles for the review.

Fixing testNonHighwayConditionallyClosed() makes ferries fail. A way of solving it would be to change (FootFlagEncoder.java)
```
        if (!acceptPotentially.canSkip()) {
            if (way.hasTag(restrictions, restrictedValues))
                return isRestrictedWayConditionallyPermitted(way, acceptPotentially);
            return isPermittedWayConditionallyRestricted(way);
        }
```
with
```
        if (!acceptPotentially.canSkip()) {
            if (way.hasTag(restrictions, restrictedValues))
                return isRestrictedWayConditionallyPermitted(way, acceptPotentially);
            return isPermittedWayConditionallyRestricted(way, acceptPotentially);
        }
```

However, that function does not exist. One could create it by changing AbstractFlagEncoder.java in the Graphhopper repo, by adding it like this:
```
    public EncodingManager.Access isPermittedWayConditionallyRestricted(ReaderWay way, EncodingManager.Access accept) {
        return getConditionalAccess(way, accept, false);
    }
```

Should I make a PR at the GIScience/graphhopper repo to create those changes? Or is it better to just add the changes in FootFlagEncoder as it implements AbstractFlagEncoder?

Best,
Héctor

**Comment by Robot8A** [comment]
In the end I added it to this repo, with a TODO comment to add it later into graphhopper.

**Comment by aoles** [comment]
Dear Héctor,

Thanks a lot for your updates, this looks great! 

Would you still mind moving the new method `isPermittedWayConditionallyRestricted` from `ORSAbstractFlagEncoder` to `AbstractFlagEncoder` as described in your TODO comment? I think the current stripped down implementation actually fails to flag the ways which are tagged with conditional access as identified by `conditionalTagInspector.hasLazyEvaluatedConditions`.

Looking forward to your corresponding PR in https://github.com/GIScience/graphhopper.

Cheers!
Andrzej

**Comment by Robot8A** [comment]
https://github.com/GIScience/graphhopper/pull/53

**Comment by takb** [comment]
I just merged **https://github.com/GIScience/graphhopper/pull/53**, next update the references in openrouteservice/pom.xml to  
[v0.13.23](https://github.com/GIScience/graphhopper/releases/tag/v0.13.23)

**Comment by aoles** [comment]
Dear Héctor,

could you please adapt the ORS code to use the new method introduced in https://github.com/GIScience/graphhopper/pull/53?

Cheers!

**Comment by Robot8A** [comment]
Done!

**Comment by Robot8A** [comment]
Done!

**Comment by aoles** [comment]
Awesome, thanks a lot for your prompt update! 👍 

One last thing I've just noticed: as you have introduced the method `FootFlagEncoder.setProperties`, would you mind for the sake of being consistent to use it in `HikingFlagEncoder` as well?

Cheers!

**Comment by Robot8A** [comment]
I have added a new setProperties that includes a boolean to change the block_fords behaviour. Should I leave it how I have done it, take block fords completely from setProperties, or make the HikingFlagEncoder override the default later? The original FootFlagEncoder setProperties (with one parameter) was adapted from VehicleFlagEncoder.
Best.

**Comment by aoles** [comment]
Thanks for getting back to me so quickly. I would suggest yet another solution, namely modify `setProperties(PMap properties)` method to call `setProperties(properties, true)`. Cheers!

**Comment by Robot8A** [comment]
Sure, sounds right! Done.

**Review by aoles — APPROVED** [review]
Perfect! Thanks again for your contribution @Robot8A.

@takb I think the PR is ready to be merged now.

Cheers!

**Pull request merged**
