### PR TITLE
refactor: remove unused AccelerationWeighting

### PR DESCRIPTION
**Pull request by sfendrich**
The class AccelerationWeighting is unfinished since 2017 and, therefore, removed as unused code.

### Pull Request Checklist

- [x] 1. I have [**rebased**][rebase] the latest version of the master branch into my feature branch and all conflicts
         have been resolved.
- [x] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the
         [Unreleased] heading.
- [ ] 3. I have documented my code using JDocs tags.
- [ ] 4. I have removed unnecessary commented out code, imports and System.out.println statements.
- [ ] 5. I have written JUnit tests for any new methods/classes and ensured that they pass.
- [ ] 6. I have created API tests for any new functionality exposed to the API.
- [ ] 7. If changes/additions are made to the ors-config.json file, I have added these to the [ors config documentation][config]
         along with a short description of what it is for, and documented this in the Pull Request (below).
- [x] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [ ] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [ ] 10. For new features or changes involving building of graphs, I have tested on a larger dataset
          (at least Germany), and the graphs build without problems (i.e. no out-of-memory errors).
- [ ] 11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the
          importer etc.), I have generated longer distance routes for the affected profiles with different options
          (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end
          points generated from the current live ORS.
          If there are differences then the reasoning for these **MUST** be documented in the pull request.
- [x] 12. I have written in the Pull Request information about the changes made including their intended usage
          and why the change was needed.
- [ ] 13. For changes touching the API documentation, I have tested that the API playground [renders correctly][api].

### CODE REVIEW

**Comment by sfendrich** [comment]
This is not a refactoring because the fix changes the behavior of ORSWeightingFactory. Hence the rename from fix to refactor should be reverted.

**Comment by MichaelsJP** [comment]
@sfendrich What are your thoughts on waiting for refactorings like this after the modularization branch is merged? 
I can imagine it will make merging quite difficult, and I guess your commit history will almost likely be overridden.

@takb @jlink  Your thoughts on this?

**Comment by sfendrich** [comment]
I'm fine with waiting. Just had a bit of time left and thought this would be a good opportunity for minor cleanup.

**Comment by jlink** [comment]
> @sfendrich What are your thoughts on waiting for refactorings like this after the modularization branch is merged? I can imagine it will make merging quite difficult, and I guess your commit history will almost likely be overridden.
> 
> @takb @jlink Your thoughts on this?

My impression, when we discussed it last week, was that there will be a 7.x release very soon so that the modularization PR can be merged right after that. Any new change will potentially create a merge conflict because EVERY JAVA FILE (and most other files) are in a different place now and the pom(s) have also changed in subtle and not so subtle ways.

**Comment by takb** [comment]
I don't think this needs to wait, the merge of the modularization branch will be non-trivial anyway

**Review by takb — APPROVED** [review]
Yes!

**Comment by jlink** [comment]
> I don't think this needs to wait, the merge of the modularization branch will be non-trivial anyway

IMO. Not an argument for making it worse and worse.

**Pull request merged**
