### PR TITLE
Fix for `access: destination`

### LINKED ISSUE #253: Rework the motor_vehicle=destination tag penalty logic
Consider driving on the following [field road](https://www.openstreetmap.org/way/157774067).

https://maps.openrouteservice.org/directions?n1=49.490536&n2=8.65129&n3=17&a=49.490507,8.654737,49.490417,8.647077&b=0&c=0&k1=en-US&k2=km

image

The reported driving time for 553 meters is 6 minutes, which translates into a driving speed of about 5 km/h. When switched to `profile=driving-hgv` the time reduces to a more reasonable value of 1 minute. Switching between CH and ALT by enabling some filters does not change these values.

Now, when the distance between the start and end points is slightly increased e.g. by dragging the former point a bit to the left the returned route for `driving-car` switches to the following one; the routing for `driving-hgv` is not affected by this.

https://maps.openrouteservice.org/directions?n1=49.489629&n2=8.650542&n3=16&a=49.490507,8.654737,49.490403,8.646863&b=0&c=0&k1=en-US&k2=km

image

### LINKED ISSUE #705: Use priority weighting to discourage routing over `access=destination` ways
Routing over ways tagged with `access=destination` is currently discouraged by artificially limiting the travel speed to `destination_speed`. The problem with this approach is:
1. It introduces a spurious time penalty for `fastest` weighting reflected in inaccurate travel time estimation
2. It doesn't solve the issue for `shortest` weighting + has the same problem with travel time estimation as for `fastest`.

Investigate whether an approach of penalizing `access:destination` with priority weighting wouldn't be better. The priority of such ways could be set to `WORST`.

Should help to address https://github.com/GIScience/openrouteservice/issues/253.

### LINKED ISSUE #1061: `access=destination` speed of 5 km/h too low?
A user commentary in our [forum](https://ask.openrouteservice.org/t/route-returns-very-slow-driving-rate/3151) reported unusually long drive times on a highway that turned out to be tagged with `access:destination`.

The ors uses a speed of 5 km/h for such routes, compare https://github.com/GIScience/openrouteservice/blob/37fca1d1b6bf1203deb69c4a1ec6633248a725f8/openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/flagencoders/VehicleFlagEncoder.java#L157. 

This particular highway has a maxspeed of 45 mph, but the more general question is whether a speed of 5 km/h is justified for roads with `access:destination`.

### LINKED ISSUE #1344: access:destination - remove GH penalty
currently a double penalty both in GH and ORS is done.
Move to previous impl. to reduce differences in results.

- [ ] test locally
- [ ] check output visually
- [ ] merge if ok

touches #1061

### PR DESCRIPTION
**Pull request by aoles**
### Pull Request Checklist

- [x] 1. I have [**rebased**][rebase] the latest version of the master branch into my feature branch and all conflicts
         have been resolved.
- [ ] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the
         [Unreleased] heading.
- [x] 3. I have documented my code using JDocs tags.
- [ ] 4. I have removed unnecessary commented out code, imports and System.out.println statements.
- [x] 5. I have written JUnit tests for any new methods/classes and ensured that they pass.
- [ ] 6. I have created API tests for any new functionality exposed to the API.
- [ ] 7. If changes/additions are made to the ors-config.json file, I have added these to the [ors config documentation][config]
         along with a short description of what it is for, and documented this in the Pull Request (below).
- [x] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [x] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [ ] 10. For new features or changes involving building of graphs, I have tested on a larger dataset
          (at least Germany), and the graphs build without problems (i.e. no out-of-memory errors).
- [ ] 11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the
          importer etc.), I have generated longer distance routes for the affected profiles with different options
          (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end
          points generated from the current live ORS.
          If there are differences then the reasoning for these **MUST** be documented in the pull request.
- [x] 12. I have written in the Pull Request information about the changes made including their intended usage
          and why the change was needed.
- [ ] 13. For changes touching the API documentation, I have tested that the API playground [renders correctly][api].

Fixes #1344
fixes #1061 
fixes #705 
fixes #253 

### Information about the changes

- [x] fix routing 
- [ ] fix isochrones
- [ ] other occurrences of `FastestWeighting`

[config]: https://GIScience.github.io/openrouteservice/installation/Configuration.html
[api]: https://gitlab.gistools.geog.uni-heidelberg.de/giscience/openrouteservice-infrastructure/ors-docs-api#test-new-ors-documentation
[rebase]: https://github.com/GIScience/openrouteservice/blob/master/CONTRIBUTE.md#pull-request-guidelines

### CODE REVIEW

**Comment by sfendrich** [comment]
I wonder why the design change of the weighting factory is necessary for introducing the access:destination weighting. Shouldn't these be two separate things?

Further, the "cleanup" feels like a step backwards. We moved away from that design in the past to improve maintainability.

**Comment by aoles** [comment]
Thanks @sfendrich ! Of course, strictly speaking the refactoring is not necessary for the introduction of the additional weighting. However, what was necessary was the introduction of yet another hook in the upstream class in order to override the creation of the `"fastest"` weighting. To be honest, at that point with the rest of modifications to the super class it didn't make much sense to me personally to extend the superclass anymore. FWAIU we moved away from the previous design primarily because back then it was a bit unclear what parts of the original ORS weighting factory were different and necessary compared to the GH's one. Because of the insights we have gained by now I don't think this point is valid anymore. I believe the net outcome of this refactoring is in fact reduced code complexity which should also help maintainability, c.f. https://github.com/GIScience/graphhopper/pull/66.

**Comment by sfendrich** [comment]
The main reason, why we have all these hooks is that ORS is split into two code bases. The refactoring was done to ease merging them, which was the plan at least at that time. So the main question is, how do we want to proceed with the splitted code bases?

**Comment by aoles** [comment]
Sure, but even if the code bases are to be merged, these injection points won't go away or do I miss sth?

**Comment by aoles** [comment]
@sfendrich please let me know how you would like to proceed about this. If you wish, I can roll back all the refactoring. However, this will have the consequence that changes to GH's `DefaultWeightingFactory` will be necessary. These in turn will require releasing an updated GH version for this PR to work. Cheers!

**Comment by sfendrich** [comment]
Whether the injection points go away depends on the injection points and on our goals. We might want to keep some for modularity. However, some of them can easily be removed after the merge (see the comments in the source code of the PR you have linked) because the core classes may be moved into the appropriate packages and will then be accessible from within the core. Changes to GH can then be integrated properly. E.g., moving the weightings into the right package would make them available to the weighting factory, so the changes could be applied there directly. Instead we need hooks to break these dependencies because the ORS  weightings are inaccessible external classes.
If we revert the hooks now, we will have to re-iterate on this after the merge in order to do a proper integration. IMO we could avoid this ping pong between two temporary solutions.

I think this should be decided in the team meeting tomorrow.

**Comment by MichaelsJP** [comment]
@aoles Can we change it to "Ready for review" then?

**Comment by MichaelsJP** [comment]
@aoles Will this be closed as well with this logic?
- https://github.com/GIScience/openrouteservice/issues/1061
- https://github.com/GIScience/openrouteservice/issues/705
- https://github.com/GIScience/openrouteservice/issues/253

**Comment by aoles** [comment]
@MichaelsJP Yes, I hope so 🤞

**Review by MichaelsJP — APPROVED** [review]

**Pull request merged**
