### PR TITLE
Issue#1391:  support docker images for arm64

### LINKED ISSUE #1391: High graph building/response time on Apple Silicon Processors
While trying to start custom ORS docker image (built on top of the public image), on Silicon M1 Macbook Pro, we face too long graph building times for a 2GB osm.pbf file.

The same process on an EC2 ubuntu instance, with even lower specs, takes about 10 minutes, using the same Xms and Xmx heap size (`-Xms5g -Xmx7g` for 2GB osm.pbf file)

And even when the graphs are finally built and the service is up and running, the reponse times are higher than on the ubuntu EC2.
Given this difference in performance, we suspect that the delay is caused by docker engine running in compatibility/emulation mode on the macbook pro, as the ORS images are built only for `linux/amd64` architecture.

---

A solution to this, is updating ORS' CI pipeline to build and publish images for `linux/arm64` too,  apart from `linux/amd64` architecture only.
This will remove the need to run the images on Silicon processors in compatibility/emulation mode.

---

It is easy to change this by updating the following two variables on CI:

* [BUILD_PLATFORMS](https://github.com/GIScience/openrouteservice/blob/master/.github/workflows/build-and-publish.yml#L12)

* [DOCKER_PLATFORMS](https://github.com/GIScience/openrouteservice/blob/master/.github/workflows/publish-tagged-release.yml#L47)

from `linux/amd64` to `linux/amd64,linux/arm64`

The final image will be compatible with both platforms, with the correct version automatically pulled

### PR DESCRIPTION
**Pull request by rolkool**
### Pull Request Checklist

- [x] 1. I have [**rebased**][rebase] the latest version of the master branch into my feature branch and all conflicts
         have been resolved.
- [ ] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the
         [Unreleased] heading.
- [ ] 3. I have documented my code using JDocs tags.
- [ ] 4. I have removed unnecessary commented out code, imports and System.out.println statements.
- [ ] 5. I have written JUnit tests for any new methods/classes and ensured that they pass.
- [ ] 6. I have created API tests for any new functionality exposed to the API.
- [ ] 7. If changes/additions are made to the ors-config.json file, I have added these to the [ors config documentation][config]
         along with a short description of what it is for, and documented this in the Pull Request (below).
- [ ] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [x] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [ ] 10. For new features or changes involving building of graphs, I have tested on a larger dataset
          (at least Germany), and the graphs build without problems (i.e. no out-of-memory errors).
- [ ] 11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the
          importer etc.), I have generated longer distance routes for the affected profiles with different options
          (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end
          points generated from the current live ORS.
          If there are differences then the reasoning for these **MUST** be documented in the pull request.
- [ ] 12. I have written in the Pull Request information about the changes made including their intended usage
          and why the change was needed.
- [ ] 13. For changes touching the API documentation, I have tested that the API playground [renders correctly][api].

Fixes #1391 .

Adds support for arm64 docker images (e.g: for Apple Silicon M1 processors)

### CODE REVIEW

**Comment by MichaelsJP** [comment]
@rolkool Thanks for opening the PR :). We'll review it later today.

**Comment by MichaelsJP** [comment]
The problem is probably that the image is built with `arm64` and `--load` on a non arm64 platform. `--load` is needed to be able to run the docker image in the workflow.

A solution could be to have to buildx calls. 

I'll need to spend a few thoughts on this.

**Comment by MichaelsJP** [comment]
Ok. Just had an idea. Best would be to change the build process into a matrix build strategy. What I mean can be seen here for example: https://github.com/Overv/openstreetmap-tile-server/actions/runs/2694331977/workflow.

We could adapt that.

To be able to also start the runner with the right platform we need this crucial task
```yaml
-     name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: ${{ matrix.arch }}
```

**Comment by rolkool** [comment]
@MichaelsJP I think we can use only amd64 for build step, and both platforms for `publish_docker` job

**Comment by MichaelsJP** [comment]
> @MichaelsJP I think we can use only amd64 for build step, and both platforms for `publish_docker` job

Generally yes, but I still think it's important to see the docker checks run on all platforms that we build images for. Not only amd64.

**Comment by MichaelsJP** [comment]
I mean this part specifically, that should be running and passing on all platforms
```yaml
      - name: Start container from image and wait for successful checks
        run: |
          mkdir $(pwd)/graphs $(pwd)/conf
          sudo chown 1000:1000 $(pwd)/graphs $(pwd)/conf
          docker run -it -d -p 8080:8080 -v $(pwd)/graphs:/home/ors/ors-core/data/graphs -v $(pwd)/conf:/home/ors/ors-conf --name ors-instance ${{ needs.prepare_environment.outputs.test_image_name }}
          # Check for health to turn 200 after the graphs are build and spring-boot completely started         
          ./.github/utils/url_check.sh 127.0.0.1 8080 /ors/v2/health 200 240
          # Check for correct preflight settings to avoid CORS issues with ORIGIN wildcard from the example config
          ./.github/utils/cors_check.sh 127.0.0.1 8080 /ors/v2/isochrones/geojson "https://example.org" 200 10
          ./.github/utils/cors_check.sh 127.0.0.1 8080 /ors/v2/isochrones/geojson "https://example.com" 200 10
          # Adjust the config file and set ORIGIN to https://example.org
          sudo sh -c 'jq ".ors.api_settings.cors.allowed.origins[0] = \"https://example.org\"" ./conf/ors-config.json | sponge ./conf/ors-config.json'
          # Restart the container to apply the config changes
          docker restart ors-instance
          # Request preflight with https://example.com and https://example.org to see if it gets applied correctly
          ./.github/utils/cors_check.sh 127.0.0.1 8080 /ors/v2/isochrones/geojson "https://example.org" 200 50
          # It should fail with http code 403 for https://example.com since the Origin is not covered.
          ./.github/utils/cors_check.sh 127.0.0.1 8080 /ors/v2/isochrones/geojson "https://example.com" 403 10
```

**Comment by MichaelsJP** [comment]
@rolkool Look here https://github.com/GIScience/openrouteservice/pull/1407
It's implemented now.

**Comment by MichaelsJP** [comment]
@rolkool You should be able to use nightly soon with the latest arm64 platform.

**Comment by hbilgrami1** [comment]
@MichaelsJP I tried to pull the nightly version ` docker pull openrouteservice/openrouteservice:nightly --platform linux/arm64` but there was no matching manifest in the entries. Any thoughts?
`no matching manifest for linux/arm64 in the manifest list entries`

**Pull request closed without merging**
