### PR TITLE
bugfix-#533-wrong-gpx

### PR DESCRIPTION
**Pull request by rabidllama**
Adding contents of PR #543 to development branch

### CODE REVIEW

**Comment by rabidllama** [comment]
@MichaelsJP - please check to make sure that all changes are being carried across in the PR

**Comment by MichaelsJP** [comment]
@rabidllama Yeah, the PR looks good, besides you completely removed the `testGpxSchema()` which is present in `development` and should be in there. Or was that the root of the problem? We shouldn't leave that test out.

**Comment by rabidllama** [comment]
No, the testGPXSchema method was not part of your commit - that is already in development from #496 back 2 months ago (around line 450)

**Comment by MichaelsJP** [comment]
Yep, right. My mistake. It looks good :+1:

**Review by MichaelsJP — APPROVED** [review]

**Pull request merged**
