### PR TITLE
set HGV speed calculation parameter in app.config.sample

### LINKED ISSUE #806: API Playground Results vs Self Hosted very different (Durations)
#### Here's what I did
I spun up a linux VM as I needed to produce distance/duration metrics for around 65000 location pairs.  I could not run using the online version due to rate limits so spinning up my own version for this batch seemed like the easiest route.

I download the latest PBF file for Australia from http://download.geofabrik.de/australia-oceania/australia.html, spun up the docker image using the documentaion provided on your site and enabled the HGV profile.

---
#### Here's what I got
After running the batch, I noticed that the distances matches spot on to the online API playground, but the durations were very different. (much faster).

I checked a few samples using Google Maps too and Google Maps matches the API Playground durations.  Why would my self-hosted version produce much different duration results?

I have used the sample App.Config provided and made a single change to enable HGV profile.

**produced from my version**
`"durations": [
        [
            0.0,
            2809.81
        ],
        [
            2566.62,
            0.0
        ]
    ],
    "distances": [
        [
            0.0,
            51378.84
        ],
        [
            48858.77,
            0.0
        ]
    ],`

**produced from your API Playground**

`"durations": [
        [
            0.0,
            3426.16
        ],
        [
            3316.46,
            0.0
        ]
    ],
    "distances": [
        [
            0.0,
            51375.32
        ],
        [
            48847.5,
            0.0
        ]
    ]`

**request for both**
`{
  "locations": [
    [
      150.8144, -33.7861
    ],
    [
      150.7284, -34.0703
    ]
  ],
  "metrics": [
    "distance",
    "duration"
  ]
}`

### PR DESCRIPTION
**Pull request by takb**
### Pull Request Checklist

- [x] 1. I have [**rebased**](https://github.com/GIScience/openrouteservice/blob/master/CONTRIBUTE.md#pull-request-guidelines) the latest version of the master branch into my feature branch and all conflicts have been resolved.
- [x] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the [Unreleased] heading.
- [ ] 3. I have documented my code using JDocs tags.
- [x] 4. I have removed unnecessary commented out code, imports and System.out.println statements.
- [ ] 5. I have written JUnit tests for any new methods/classes and ensured that they pass.
- [ ] 6. I have created API tests for any new functionality exposed to the API.
- [ ] 7. If changes/additions are made to the app.config file, I have added these to the app.config wiki page on github along with a short description of what it is for, and documented this in the Pull Request (below).
- [x] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [x] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [ ] 10. For new features or changes involving building of graphs, I have tested on a larger dataset (at least Germany) and the graphs build without problems (i.e. no out-of-memory errors).
- [ ] 11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the importer etc.), I have generated longer distance routes for the affected profiles with different options (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end points generated from the current live ORS. If there are differences then the reasoning for these **MUST** be documented in the pull request.
- [ ] 12. I have written in the Pull Request information about the changes made including their intended usage and why the change was needed.

Fixes #806 .

### Information about the changes
- Reason for change:
app.config.sample HGV profile has now same settings regarding speed calculation as public API, to avoid user confusion.

### CODE REVIEW

**Comment by aoles** [comment]
I don't immediately see how this is linked to #806. `maximum_speed_lower_bound` is only relevant for CALT preparation and can make a difference only for queries with `maximum_speed` set. The referenced issue never mentions this parameter.

**Comment by takb** [comment]
Then I've got something mixed up while trying to reproduce the discrepancy, back to trials...

**Comment by aoles** [comment]
`use_acceleration=false` is for 99,9% the reason for the observed discrepancies...

**Comment by takb** [comment]
confirmed, thx - it got me confused because I'd set all parameters that were different from my local app.config, and it took almost an hour between each test run...

**Review by aoles — CHANGES_REQUESTED** [review]
Thanks for cleaning-up the sample config file! I have the following improvement suggestions. 

First of all, I believe that if we enable acceleration for hgv, then we should do the same for the car profile as well. At least `use_acceleration=true` is what both profiles have set in production.

Secondly, I'm not sure why the hgv profile has both `lm` and `core` preparations enabled. I would keep only the latter one unless there are reasons to keep them both. 

Last but not least, `maximum_speed_lower_bound` should remain unset for all profiles.

Cheers,
Andrzej

**Review by aoles — APPROVED** [review]
Looks perfect now, thanks a million! :)

**Pull request merged**
