### PR TITLE
Fixes tomcat cors issue

### PR DESCRIPTION
**Pull request by TimMcCauley**

### CODE REVIEW

**Comment by marq24** [comment]
to be honest - I am not a tomcat expert - BUT I can confirm that changing 
cors.support.credentials from 'true' to 'false' does not break here my local testing environment...

**Review by marq24 — APPROVED** [review]
to be honest - even after reading https://bz.apache.org/bugzilla/show_bug.cgi?id=62343 - I am not 100% sure what's broken - nor what to test in order to confirm 'as fixed'

**Comment by TimMcCauley** [comment]
@marq24 this error is raised when using the tomcat image from docker which makes sense. When you deploy locally we probably use a different build from mvn central. @masain is getting the following error now when building the war:

https://repo.maven.apache.org/maven2/com/github/GIScience/graphhopper/graphhopper-reader-osm/v0.9.14/graphhopper-reader-osm-v0.9.14.pom can't be found 

Which one shall we use?

```<dependency>
	 	<groupId>com.github.GIScience.graphhopper</groupId>
		<artifactId>graphhopper-core</artifactId>
	   	<version>v0.9.14</version>
	</dependency>

    <dependency>
		<groupId>com.github.GIScience.graphhopper</groupId>
		<artifactId>graphhopper-reader-osm</artifactId>
		<version>v0.9.14</version>
    </dependency>```

**Comment by marq24** [comment]
well the ors gh jar's are not located in/on maven central (our stuff can be found in the https://jitpack.io repro)

https://jitpack.io/com/github/GIScience/graphhopper/v0.9.14/graphhopper-v0.9.14.pom

but since I currently have temp issues with https://jitpack.io/ - this could be the root of the build probleme?

https://jitpack.io/com/github/GIScience/graphhopper/graphhopper-reader-osm/v0.9.14/graphhopper-reader-osm-v0.9.14.pom

https://jitpack.io/com/github/GIScience/graphhopper/graphhopper-core/v0.9.14/graphhopper-core-v0.9.14.pom

**Comment by TimMcCauley** [comment]
@marq24 I understand, this is the one half of the problem. What I was referring to is why your local tomcat is running, this is most likely the case because you are sourcing a different tomcat build and not from docker hub.

**Comment by TimMcCauley** [comment]
As jitpack is working again - @masain can you please try this branch once more and let us know if it goes through?

**Pull request merged**
