### PR TITLE
Support Avoid Areas for Matrix Requests

### PR DESCRIPTION
**Pull request by Nakaner**
This pull requests add support for avoid polygons for the matrix request.

Without avoid area:

```sh
curl 'http://localhost:8081/ors/v2/matrix/driving-car' -H 'Accept: application/json, text/plain, */*' -H 'Content-Type: application/json;charset=utf-8' --data-raw '{"metrics":["distance", "duration"],"locations":[[8.6793, 49.4131], [8.6871, 49.4203]]}' | jq .
```

```json
{
  "durations": [
    [
      0,
      313.08
    ],
    [
      218.75,
      0
    ]
  ],
  "distances": [
    [
      0,
      2891.58
    ],
    [
      1528.11,
      0
    ]
  ],
  "destinations": [
    {
      "location": [
        8.679376,
        49.413107
      ],
      "snapped_distance": 5.54
    },
    {
      "location": [
        8.687114,
        49.420241
      ],
      "snapped_distance": 6.69
    }
  ],
  "sources": [
    {
      "location": [
        8.679376,
        49.413107
      ],
      "snapped_distance": 5.54
    },
    {
      "location": [
        8.687114,
        49.420241
      ],
      "snapped_distance": 6.69
    }
  ],
  "metadata": {
    "attribution": "openrouteservice.org, OpenStreetMap contributors",
    "service": "matrix",
    "timestamp": 1598868646134,
    "query": {
      "locations": [
        [
          8.6793,
          49.4131
        ],
        [
          8.6871,
          49.4203
        ]
      ],
      "profile": "driving-car",
      "responseType": "json",
      "metricsStrings": [
        "DISTANCE",
        "DURATION"
      ],
      "metrics": [
        "distance",
        "duration"
      ]
    },
    "engine": {
      "version": "6.2.1",
      "build_date": "2020-08-31T09:21:46Z",
      "graph_date": "2020-08-31T09:23:38Z"
    }
  }
}

```

With avoid area:

```sh
curl 'http://localhost:8081/ors/v2/matrix/driving-car' -H 'Accept: application/json, text/plain, */*' -H 'Content-Type: application/json;charset=utf-8' --data-raw '{"metrics":["distance"],"locations":[[8.6793, 49.4131], [8.6871, 49.4203]],"avoid_areas": {"avoid_polygons": {"type": "Polygon", "coordinates": [ [ [8.6689,49.4156], [8.6689,49.4179], [8.6891,49.4179], [8.6891,49.4156], [8.6689,49.4156] ] ]}} }' | jq .
```

```json
{
  "durations": [
    [
      0,
      380.48
    ],
    [
      348.47,
      0
    ]
  ],
  "distances": [
    [
      0,
      2486.09
    ],
    [
      1837.95,
      0
    ]
  ],
  "destinations": [
    {
      "location": [
        8.679376,
        49.413107
      ],
      "snapped_distance": 5.54
    },
    {
      "location": [
        8.687114,
        49.420241
      ],
      "snapped_distance": 6.69
    }
  ],
  "sources": [
    {
      "location": [
        8.679376,
        49.413107
      ],
      "snapped_distance": 5.54
    },
    {
      "location": [
        8.687114,
        49.420241
      ],
      "snapped_distance": 6.69
    }
  ],
  "metadata": {
    "attribution": "openrouteservice.org, OpenStreetMap contributors",
    "service": "matrix",
    "timestamp": 1598868586785,
    "query": {
      "locations": [
        [
          8.6793,
          49.4131
        ],
        [
          8.6871,
          49.4203
        ]
      ],
      "profile": "driving-car",
      "responseType": "json",
      "metricsStrings": [
        "DISTANCE",
        "DURATION"
      ],
      "metrics": [
        "distance",
        "duration"
      ],
      "avoid_areas": {
        "avoid_polygons": {
          "coordinates": [
            [
              [
                8.6689,
                49.4156
              ],
              [
                8.6689,
                49.4179
              ],
              [
                8.6891,
                49.4179
              ],
              [
                8.6891,
                49.4156
              ],
              [
                8.6689,
                49.4156
              ]
            ]
          ],
          "type": "Polygon"
        }
      }
    },
    "engine": {
      "version": "6.2.1",
      "build_date": "2020-08-31T09:21:46Z",
      "graph_date": null
    }
  }
}
```

### CODE REVIEW

**Comment by jcoupey** [comment]
I'm trying to test this out but the above `curl` command results in an error:

```bash
$curl 'http://localhost:8080/ors/v2/matrix/driving-car' -H 'Accept: application/json, text/plain, */*' -H 'Content-Type: application/json;charset=utf-8' --data-raw '{"metrics":["distance"],"locations":[[8.6793, 49.4131], [8.6871, 49.4203]],"avoid_areas": {"avoid_polygons": {"type": "Polygon", "coordinates": [ [ [8.6689,49.4156], [8.6689,49.4179], [8.6891,49.4179], [8.6891,49.4156], [8.6689,49.4156] ] ]}} }' | jq .
{
  "error": {
    "code": 6011,
    "message": "Unknown parameter 'avoid_areas'."
  }
[...]
}
```

I'm not an Openrouteservice heavy user so I may have missed something in the setup. What I did:

- clone Nakaner/openrouteservice and checkout the `matrix-avoid-areas` branch
- adjust `docker/docker-compose.yml` to build an image with the current code (comment the `image` line and uncomment the `build` section)
- run `docker-compose up`

**Comment by Nakaner** [comment]
@jcoupey wrote:
> I'm trying to test this out but the above `curl` command results in an error:
> 
> ```shell
> $curl 'http://localhost:8080/ors/v2/matrix/driving-car' -H 'Accept: application/json, text/plain, */*' -H 'Content-Type: application/json;charset=utf-8' --data-raw '{"metrics":["distance"],"locations":[[8.6793, 49.4131], [8.6871, 49.4203]],"avoid_areas": {"avoid_polygons": {"type": "Polygon", "coordinates": [ [ [8.6689,49.4156], [8.6689,49.4179], [8.6891,49.4179], [8.6891,49.4156], [8.6689,49.4156] ] ]}} }' | jq .
> {
>   "error": {
>     "code": 6011,
>     "message": "Unknown parameter 'avoid_areas'."
>   }
> [...]
> }
> ```
> 
> I'm not an Openrouteservice heavy user so I may have missed something in the setup. What I did:
> 
>     * clone Nakaner/openrouteservice and checkout the `matrix-avoid-areas` branch
> 
>     * adjust `docker/docker-compose.yml` to build an image with the current code (comment the `image` line and uncomment the `build` section)
> 
>     * run `docker-compose up`

Did remove previous Openrouteservice Docker images and containers? If you have build an Openrouteservice Docker image before, `docker-compose up -d` might pick up the old one. Did you remove graphs, old config etc. from the `docker/` subdirectory? `docker/graphs`, `docker/logs` etc. are mounted as volumes into the Docker container, see `docker-compose.yml` for details. Note: You have to remove the directory `sudo rm -rf docker/graphs docker/logs docker/data docker/conf docker/elevation_cache` because running Docker afterwards might fail.

**Comment by jcoupey** [comment]
>Did remove previous Openrouteservice Docker images and containers?

The weird part is I don't have a previous Docker image built from the repo. I just retried the process in a new folder with:

```
git worktree add my_folder 13241fbc
cd my_folder/docker
# edit docker-compose.yml
sudo docker-compose up
```

Anyway this has probably more to do with the docker setup than with your actual work on this PR, so might be a bit off-topic here.

**Comment by nilsnolde** [comment]
@Nakaner looks interesting! I'm not a reviewer, but did you do some performance testing on this? e.g. 10, 20, 50 locations with each (on average) 10,20,50,100 km routes? I guess the performance is (expectedly) suffering a lot compared to static matrix calculations, but having a few house numbers would be very good.

@rabidllama @HendrikLeuschner what do you think about this functionality? I guess #385 might eventually supercede this work (hopefully:)).

@jcoupey I'll try dockerizing it myself once I know it's worth it and let you know.

**Comment by Nakaner** [comment]
> @Nakaner looks interesting! I'm not a reviewer, but did you do some performance testing on this? e.g. 10, 20, 50 locations with each (on average) 10,20,50,100 km routes? I guess the performance is (expectedly) suffering a lot compared to static matrix calculations, but having a few house numbers would be very good.

The following modifications are necessary for the following test:

```
ors.services.matrix.maximum_routes = 10000
ors.services.matrix.maximum_visited_nodes = 10000000
ors.services.routing.maximum_distance_avoid_areas = 200000
ors.services.routing.maximum_avoid_polygon_area = 2000000000
ors.services.routing.maximum_avoid_polygon_extent = 200000
```

Profile: driving-car

Regierungsbezirk Freiburg (Baden-Württemberg, Germany), 117 MB .osm.pbf, 475394 edges, 376697 nodes:

Test with 10 points and an avoid area outside the area covered by the graph (Liechtenstein) takes 4.7 seconds:

```json
{"metrics": ["distance", "duration"], "locations": [["7.7069", "47.7334"], ["8.1629", "47.9519"], ["7.6829", "47.8155"], ["8.0764", "48.0929"], ["8.1556", "47.6874"], ["8.8986", "47.7567"], ["7.8168", "48.2903"], ["8.2564", "48.4856"], ["7.9658", "48.2419"], ["8.1235", "48.3457"]], "avoid_areas": {"avoid_polygons": {"type": "Polygon", "coordinates": [[[9.5115, 47.1545], [9.5115, 47.1899], [9.5147, 47.1899], [9.5147, 47.1545], [9.5115, 47.1545]]]}}}
```

24 points and same avoid area takes 13.4 seconds:

```json
{"metrics": ["distance", "duration"], "locations": [["7.7069", "47.7334"], ["8.1629", "47.9519"], ["7.6829", "47.8155"], ["8.0764", "48.0929"], ["8.1556", "47.6874"], ["8.8986", "47.7567"], ["7.8168", "48.2903"], ["8.2564", "48.4856"], ["7.9658", "48.2419"], ["8.1235", "48.3457"], ["7.7502", "47.9808"], ["8.2612", "48.2962"], ["7.8024", "47.7402"], ["7.9097", "47.805"], ["7.9672", "47.8189"], ["8.0104", "47.862"], ["7.7861", "47.8169"], ["8.015", "47.8221"], ["7.806", "47.9851"], ["7.872", "48.044"], ["7.6694", "47.8707"], ["7.9863", "47.9231"], ["8.4501", "48.0544"], ["8.5377", "48.0671"]], "avoid_areas": {"avoid_polygons": {"type": "Polygon", "coordinates": [[[9.5115, 47.1545], [9.5115, 47.1899], [9.5147, 47.1899], [9.5147, 47.1545], [9.5115, 47.1545]]]}}}
```

24 points and an avoid area which is a small strip from far in the north to far in the south of the area (leaving at least one road around it passable) takes 11.2 seconds:

```json
{"metrics": ["distance", "duration"], "locations": [["7.7069", "47.7334"], ["8.1629", "47.9519"], ["7.6829", "47.8155"], ["8.0764", "48.0929"], ["8.1556", "47.6874"], ["8.8986", "47.7567"], ["7.8168", "48.2903"], ["8.2564", "48.4856"], ["7.9658", "48.2419"], ["8.1235", "48.3457"], ["7.7502", "47.9808"], ["8.2612", "48.2962"], ["7.8024", "47.7402"], ["7.9097", "47.805"], ["7.9672", "47.8189"], ["8.0104", "47.862"], ["7.7861", "47.8169"], ["8.015", "47.8221"], ["7.806", "47.9851"], ["7.872", "48.044"], ["7.6694", "47.8707"], ["7.9863", "47.9231"], ["8.4501", "48.0544"], ["8.5377", "48.0671"]], "avoid_areas": {"avoid_polygons": {"type": "Polygon", "coordinates": [[[8.1008,47.6155], [8.1008,48.3032], [8.1064,48.3032], [8.1064,47.6155], [8.1008,47.6155]]]}}}
```

I can run tests for whole Germany if it is desired.

**Comment by HendrikLeuschner** [comment]
Sorry for the long wait. So do I see it correctly that this creates a Dijkstra-based matrix algorithm for a request with avoid areas? Have you made sure that it does not create an RPHAST-Algorithm, that does not work with avoid areas?

**Comment by koebi** [comment]
Is this superseded by #959 @HendrikLeuschner ?

**Comment by HendrikLeuschner** [comment]
No, this is different as the affected edges are not known at preprocessing time.

**Comment by MichaelsJP** [comment]
This will potentially be addressed at a later point. Closing it for now to clean up the PR backlog.

**Comment by ClemenceAlain** [comment]
Hello ! 
I would be very interested in seeing this work finished. Not sure I have the skills but can you tell me what was missing to validate the PR ?

**Comment by nilsnolde** [comment]
FWIW, that's implemented in Valhalla in case you can stomach the matrix performance difference: https://valhalla.github.io/valhalla/api/matrix/api-reference/#costing-parameters.

EDIT: never mind, just seeing this functionality is of course not possible in the fast matrix algo. So Valhalla should even be quite a bit faster with its bidir A* matrix than this PR (dijkstra).

**Comment by MichaelsJP** [comment]
@ClemenceAlain Thanks for tuning in!

We recently spent a lot of time researching routing algorithms that meet our standards for performance and scalability with avoid areas. It's not clear from this page.

**Why we haven’t merged this PR:**  
*Current options*, including A* and Dijkstra, **don’t meet our performance and scalability requirements**, especially with *large, complex, or many avoid areas*. That’s why we have chosen not to enable this for matrix calculations yet.

We’re currently exploring a promising alternative that *might* make routing with complex avoids fast and scalable enough to combine with matrices. 
**The next months will tell.**

For now, Bidirectional A* in Valhalla is likely the best fit for *simple/small avoid areas* in Matrix, but **performance drops fast** with increasing avoid complexity, numbers or size, *a general A\*-limitation*, not Valhalla-specific.

Will update this thread when we have more to show/tell.

**Pull request closed without merging**
