### PR TITLE
Refactored edgefilters

### PR DESCRIPTION
**Pull request by aoles**
### Pull Request Checklist

- [x] 1. I have merged the latest version of the development branch into my feature branch and all conflicts have been resolved
- [x] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the [Unreleased] heading
- [x] 3. I have documented my code using JDocs tags
- [x] 4. I have removed unecessary commented out code, imports and System.out.println statements
- [x] 5. I have written JUnit tests for any new methods/classes and ensured that they pass
- [x] 6. I have created API tests for any new functionality exposed to the API
- [x] 7. If changes/additions are made to the app.config file, I have added these to the app.config.sample file along with a short description of what it is for, and documented this in the Pull Request (below) 
- [x] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [x] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue)
- [x] 10. For new features involving building of graphs, I have tested on a larger dataset (at least Germany) and the graphs build without problems (i.e. no out-of-memory errors)
- [x] 11. I have written in the Pull Request information about the changes made including their intended usage and why the change was needed.

### Information about the changes
**Reason for change:** While reviewing the code of edge filters in the course of implementing filters for building the core graph for core-ALT routing I have taken the opportunity to refactor some of the original edge filters' code to simplify and clean it up, in particular:
- Code of `EdgeFilterSequence` has been refactored such that rather than including an `ArrayList` private field the class itself extends `ArrayList`. This reduces the overall code complexity by removing the need of any helper methods to manage the filter sequence in `RoutingProfile`. The change was motivated by reusing `EdgeFilterSequence` in the context of core-building filters.
- Edge direction check which was repeated in each individual filter is now taken care of by the `DefaultEdgeFilter` called as first in the sequence.
- `AvoidFeaturesEdgeFilter` has been compacted by using aggregated profile flags defined in `AvoidFeatureFlags` instead of checking for each individual feature flag separately. The same profile flags will be reused in core-building filters.
- The code of `RouteProfile.createSearchContext` has been significantly refactored to improve readability and minimize repeated method calls.
- Reduced computational complexity of `BlockedEdgesEdgeFilter` (currently not used) by switching from two separate `Lists` to a single `HashSet`. This was motivated by better performance of `contains`: O(1) compared to O(n).

### Required changes to app.config (if applicable)
- None

### Correctness

Long-distance routing tests have been performed for 100 random endpoint pairs in the DACH region for both `driving-hgv` and `cycyling-regular` profiles with various restrictions enabled. The produced routes were **identical** to the ones obtained from the development branch.

### CODE REVIEW

**Comment by rabidllama** [comment]
@marq24 Can you have a quick look over where the FlagEncoder has been removed from the methods to make sure that this won't cause giant problems when it comes to merging the changes for GH 0.10 please (I know that you have done some things for a factory of some sort for those)? I believe that it is not needed in the new version of the filters as they don't check for forwards and backwards - can you confirm @aoles , and just confirm why these are no longer needed in the filters.

**Comment by aoles** [comment]
Any `EdgeFilter`s are arranged and called in a sequence, where the first one (even if there are no other edge filters) is always the GH's `DefaultEdgeFilter`. This default filter already performs the forward/backward check. Subsequent filters are called only if this check passes, so there is no need to repeat it over and over again in each edge filter.

**Comment by marq24** [comment]
I just have checked out this branch and tried to merge it into the current WIP of our ors gh0.10.1 project - and the only merge conflict is within the ...\extentions\eddgefilters package [which seams to be logical].

I don't see any conflicts of this PR (into 0.9) that could not be merged into the ors gh0.10 - so I am fine with it

**Review by rabidllama — APPROVED** [review]

**Comment by rabidllama** [comment]
@aoles Can you just write in the PR which issue(s) it addresses so I/GitHub can update the projects accordingly thanks

**Comment by aoles** [comment]
Thanks @rabidllama! This one doesn't address any open issues, just pure code refactoring and cleanup to make it more readable and reusable (e.g use of `EdgeFilterSequence` for chaining core-building filters in core-ALT).

**Pull request merged**
