### PR TITLE
fix(matrix-algorithms): Consistent use of maximum visited nodes limit

### LINKED ISSUE #1246: RPHAST matrix algorithm does not respect config file setting of `maximum_visited_nodes`
Unlike **DijkstraMatrixAlgorithm** or **CoreMatrixAlgorithm**

https://github.com/GIScience/openrouteservice/blob/a2681643b69d74699cef5e5d028d5292030cd191/openrouteservice/src/main/java/org/heigit/ors/matrix/algorithms/dijkstra/DijkstraMatrixAlgorithm.java#L64

https://github.com/GIScience/openrouteservice/blob/a2681643b69d74699cef5e5d028d5292030cd191/openrouteservice/src/main/java/org/heigit/ors/matrix/algorithms/core/CoreMatrixAlgorithm.java#L96

the **RPHAST** matrix implementation doesn't apply the limit on the number of visited nodes specified in the config file:

https://github.com/GIScience/openrouteservice/blob/a2681643b69d74699cef5e5d028d5292030cd191/openrouteservice/src/main/java/org/heigit/ors/routing/algorithms/RPHASTAlgorithm.java#L69

I believe the configured limit should be respected regardless the actual algorithm being used to compute the result.

### PR DESCRIPTION
**Pull request by aoles**
Apply the limit on the number of visited nodes which is specified in the config file to all matrix algorithms.

### Pull Request Checklist

- [x] 1. I have [**rebased**][rebase] the latest version of the master branch into my feature branch and all conflicts
         have been resolved.
- [x] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the
         [Unreleased] heading.
- [ ] 3. I have documented my code using JDocs tags.
- [ ] 4. I have removed unnecessary commented out code, imports and System.out.println statements.
- [ ] 5. I have written JUnit tests for any new methods/classes and ensured that they pass.
- [ ] 6. I have created API tests for any new functionality exposed to the API.
- [ ] 7. If changes/additions are made to the ors-config.json file, I have added these to the [ors config documentation][config]
         along with a short description of what it is for, and documented this in the Pull Request (below).
- [x] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [x] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [ ] 10. For new features or changes involving building of graphs, I have tested on a larger dataset
          (at least Germany), and the graphs build without problems (i.e. no out-of-memory errors).
- [ ] 11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the
          importer etc.), I have generated longer distance routes for the affected profiles with different options
          (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end
          points generated from the current live ORS.
          If there are differences then the reasoning for these **MUST** be documented in the pull request.
- [x] 12. I have written in the Pull Request information about the changes made including their intended usage
          and why the change was needed.
- [ ] 13. For changes touching the API documentation, I have tested that the API playground [renders correctly][api].

Fixes #1246.

### Information about the changes
- Key functionality added: Enforce `maximum_visited_nodes` limit specified in the config file.

- Reason for change: The limit was not respected at all by **RPHAST** matrix algorithm, and not handled properly by **CoreMatrix** either.

### Examples and reasons for differences between live ORS routes, and those generated from this pull request

Some more complex long-distance matrix queries computed with either RPHAST or CoreMatrix which have been working before might start failing with the following error:
```
Unable to compute a distance/duration matrix: Search exceeds the limit of visited nodes.
```

This can be circumvented by increasing the `maximum_visited_nodes` limit if server resources allow it.

[config]: https://GIScience.github.io/openrouteservice/installation/Configuration.html
[api]: https://gitlab.gistools.geog.uni-heidelberg.de/giscience/openrouteservice-infrastructure/ors-docs-api#test-new-ors-documentation
[rebase]: https://github.com/GIScience/openrouteservice/blob/master/CONTRIBUTE.md#pull-request-guidelines

### CODE REVIEW

**Comment by MichaelsJP** [comment]
@aoles thanks for implementing this.

**Review by MichaelsJP — CHANGES_REQUESTED** [review]
I'd say we should have an integration/unit test in place checking, checking for this exception to be thrown. What do you think?

**Comment by MichaelsJP** [comment]
@aoles Any progress so far or anything I could help with?

**Comment by aoles** [comment]
Thanks @MichaelsJP , I'm good 😎 

Implementing reasonable unit tests turned out to be more effort than originally anticipated as the tests actually revealed some issues with the current implementation 🙈  Addressing these required some smart restructuring of existing methods and classes, that's why it took a bit longer. But I'm basically done now, just going through the introduced changes the last time before pushing to make sure nothing breaks 🤞

**Comment by aoles** [comment]
Unit test for exceeding the maximum number of visited nodes in RPHAST and Core matrix algorithms are now in. Regular Dijkstra matrix algorithm is currently not covered by any unit tests at all. I will look whether we could have at least an API test for it. I believe an additional integration test apart from the unit tests makes sense anyway.

**Comment by aoles** [comment]
@MichaelsJP With the API test in place, I think we are good to go now! 🚀

**Review by MichaelsJP — APPROVED** [review]

**Pull request merged**
