### PR TITLE
Create ors_id-ID.resources

### PR DESCRIPTION
**Pull request by darkshadowlho**
### Pull Request Checklist

- [x] 1. I have [**rebased**](https://github.com/GIScience/openrouteservice/blob/master/CONTRIBUTE.md#pull-request-guidelines) the latest version of the development branch into my feature branch and all conflicts have been resolved.
- [ ] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the [Unreleased] heading.
- [ ] 3. I have documented my code using JDocs tags.
- [ ] 4. I have removed unnecessary commented out code, imports and System.out.println statements.
- [ ] 5. I have written JUnit tests for any new methods/classes and ensured that they pass.
- [ ] 6. I have created API tests for any new functionality exposed to the API.
- [ ] 7. If changes/additions are made to the app.config file, I have added these to the app.config wiki page on github along with a short description of what it is for, and documented this in the Pull Request (below).
- [ ] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [ ] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [ ] 10. For new features or changes involving building of graphs, I have tested on a larger dataset (at least Germany) and the graphs build without problems (i.e. no out-of-memory errors).
- [ ] 11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the importer etc.), I have generated longer distance routes for the affected profiles with different options (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end points generated from the current live ORS. If there are differences then the reasoning for these **MUST** be documented in the pull request.
- [x] 12. I have written in the Pull Request information about the changes made including their intended usage and why the change was needed.

Fixes # .

### Information about the changes
- Translation about indonesian language has been added
- People can edit about the wrong in the language, if there is mispelling or anything wrong during tanslation

### CODE REVIEW

**Comment by darkshadowlho** [comment]
Hope translation in indo will work thanks

**Review by rabidllama — CHANGES_REQUESTED** [review]
Thanks for this, but can you please add the "default" translations as well. These basically should be the same as the "name" one, but without the part that gives the name. So for example, I assume that the turn->default property would be something like:
```
"default": {
    "default": "Belok {turn_maneuver}",
    "name": "Belok {turn_maneuver} ke {way_name}"
}
```

**Comment by darkshadowlho** [comment]
Done for it, thanks for the review

**Review by rabidllama — APPROVED** [review]

**Comment by rabidllama** [comment]
@darkshadowlho sorry just saw that there isn't anything in the changelog file for this - can you put it in please. It would also be good if once you did that you could squash the commits down into a single commit so that the commit history is nice and clean :)

**Review by rabidllama — CHANGES_REQUESTED** [review]
All looks good, but can we please get a comment into the changelog?

**Comment by darkshadowlho** [comment]
Moved to https://github.com/GIScience/openrouteservice/pull/580

**Pull request closed without merging**
