### PR TITLE
Fix the cors issues

### LINKED ISSUE #1358: Spring-boot cors configuration
Currently, the spring-boot CORS is not configured correctly.

### LINKED ISSUE #1394: CORS check for backend tomcat deployment

### PR DESCRIPTION
**Pull request by MichaelsJP**
it was previously not possible to read in list of strings from the
config file.
This can now be done in a generic way.### Pull Request Checklist

- [x] 1. I have [**rebased**][rebase] the latest version of the master branch into my feature branch and all conflicts
         have been resolved.
- [x] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the
         [Unreleased] heading.
- [x] 3. I have documented my code using JDocs tags.
- [x] 4. I have removed unnecessary commented out code, imports and System.out.println statements.
- [x] 5. I have written JUnit tests for any new methods/classes and ensured that they pass.
- [x] 6. I have created API tests for any new functionality exposed to the API.
- [ ] 7. If changes/additions are made to the ors-config.json file, I have added these to the [ors config documentation][config]
         along with a short description of what it is for, and documented this in the Pull Request (below).
- [x] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [x] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [ ] 10. For new features or changes involving building of graphs, I have tested on a larger dataset
          (at least Germany), and the graphs build without problems (i.e. no out-of-memory errors).
- [ ] 11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the
          importer etc.), I have generated longer distance routes for the affected profiles with different options
          (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end
          points generated from the current live ORS.
          If there are differences then the reasoning for these **MUST** be documented in the pull request.
- [x] 12. I have written in the Pull Request information about the changes made including their intended usage
          and why the change was needed.
- [ ] 13. For changes touching the API documentation, I have tested that the API playground [renders correctly][api].

Fixes #1394 

### Information about the changes
- Key functionality added: Correct CORS handling and configuration
- Reason for change: Currently, CORS cannot be handled correctly from the backend.

### Examples and reasons for differences between live ORS routes, and those generated from this pull request
-

### Required changes to ors config (if applicable)
```json
"api_settings": {
      "cors": {
        "allowed": {
          "origins": [
			"*",
            "https://example.org"
          ],
          "methods": [
            "GET",
            "POST",
            "OPTIONS"
          ],
          "headers": [
            "Content-Type",
            "X-Requested-With",
            "accept",
            "Origin",
            "Access-Control-Request-Method",
            "Access-Control-Request-Headers",
            "Authorization"
          ]
        },
        "exposed": {
          "headers": [
            "Access-Control-Allow-Origin", "Access-Control-Allow-Credentials"
          ]
        },
        "preflight_max_age": 600
      }
    },
```

[config]: https://GIScience.github.io/openrouteservice/installation/Configuration.html
[api]: https://gitlab.gistools.geog.uni-heidelberg.de/giscience/openrouteservice-infrastructure/ors-docs-api#test-new-ors-documentation
[rebase]: https://github.com/GIScience/openrouteservice/blob/master/CONTRIBUTE.md#pull-request-guidelines

### CODE REVIEW

**Comment by MichaelsJP** [comment]
@TheGreatRefrigerator Should we put some default values for the CORS settings?
Many users will use their old config and still have problems. We could avoid that by settings a wildcard by default?

**Comment by TheGreatRefrigerator** [comment]
> @TheGreatRefrigerator Should we put some default values for the CORS settings? Many users will use their old config and still have problems. We could avoid that by settings a wildcard by default?

Yes, the default values should mirror those we set in the sample config i guess.

**Comment by TheGreatRefrigerator** [comment]
Did some squashing and dropped the `@CrossOrigin` parts as they were overwriting the main CORS config, and resulted in further CORS Errors when pairing with the map clients.
Let's see if the new tests run through.

**Review by takb — APPROVED** [review]
LGTM. Checked locally, seems to work both in docker and run directly.

**Pull request merged**
